//! Cross-implementation vectors locking cashu-core-lite to gonuts (Go/btcec)
//! and the Python (coincurve) ports.
//!
//! Canonical source: `cashu-cross-vectors.json` in the Amperstrand workspace —
//! extend there first, mirror here, never edit existing vectors in place.
//! These vectors caught real bugs in two other implementations (prta #86's
//! original Y-derivation and a hex-decode divergence in the first Python
//! patch), so they are load-bearing interop contracts, not coverage filler.

use cashu_core_lite::crypto::{
    blind_message, hash_to_curve, sign_message, unblind_signature, verify_signature_with_privkey,
};
use cashu_core_lite::keypair::{PublicKey, SecretKey};
use cashu_core_lite::nuts::nut12::verify_dleq;

fn pk(hex_str: &str) -> PublicKey {
    let bytes = hex::decode(hex_str).expect("valid hex");
    let mut arr = [0u8; 33];
    arr.copy_from_slice(&bytes);
    PublicKey::from_bytes(&arr).expect("valid point")
}

fn sk(seed: u8) -> SecretKey {
    SecretKey::from_slice(&[seed; 32]).expect("valid scalar")
}

fn sk_from_hex(hex_str: &str) -> SecretKey {
    let bytes = hex::decode(hex_str).expect("valid hex");
    SecretKey::from_slice(&bytes).expect("valid scalar")
}

/// NUT-00 hash_to_curve must agree byte-for-byte with gonuts and the Python
/// ports. The third vector is the hex-looking-secret trap: it is a valid hex
/// string but MUST be hashed as its 64 ASCII characters — hashing the decoded
/// 32 bytes instead produces a plausible, wrong Y (this exact divergence
/// shipped in two implementations).
#[test]
fn cross_hash_to_curve_vectors() {
    let vectors = [
        (
            "test-secret-01",
            "0279110ffdbbaccf1f96e0641dd8794fb206e8f95eb52c0fa001487b070cb5f7b1",
        ),
        (
            "a",
            "029794c59a5d9b910a18e50e10623c864b77c7edf4552f8652b0c85d30ac0498f0",
        ),
        (
            "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            "0244d4bdec44e84725e2b6d9d7a2896df8bc27b482e84e0cb2144272d318375bc3",
        ),
    ];
    for (secret, expected) in vectors {
        let y = hash_to_curve(secret.as_bytes()).expect("hash_to_curve succeeds");
        assert_eq!(
            hex::encode(y.to_bytes()),
            expected,
            "hash_to_curve diverged from cross-vectors for secret {secret:?}"
        );
    }
}

/// Full NUT-00 DHKE + NUT-12 DLEQ chain, generated by this crate and
/// verified by gonuts (btcec) on 2026-08-18: gonuts accepted the DLEQ proof
/// and `crypto.Verify(secret, a, C)` accepted the unblinded signature.
#[test]
fn cross_dhke_dleq_vector_1() {
    let secret = b"cross-poll-vector-1";
    let a = sk(7);
    let a_pk = a.public_key();

    assert_eq!(
        hex::encode(a_pk.to_bytes()),
        "02989c0b76cb563971fdc9bef31ec06c3560f3249d6ee9e5d83c57625596e05f6f",
        "mint key derivation diverged"
    );

    let y = hash_to_curve(secret).unwrap();
    assert_eq!(
        hex::encode(y.to_bytes()),
        "02e525f0f3d5645e28c4956858310a5364240d40a23670006438091f1878daed2d"
    );

    let bm = blind_message(secret, Some(sk(11))).unwrap();
    assert_eq!(
        hex::encode(bm.blinded.to_bytes()),
        "02146df70db068304f8c8416d463991af9fa9a47d84be0e64bbef39636b17619cb",
        "deterministic blinding diverged"
    );

    let c_prime = sign_message(&a, &bm.blinded);
    assert_eq!(
        hex::encode(c_prime.to_bytes()),
        "0386c681c4515c1f32cb53d4cfc00cf57debe6d62a1cc52a84afe8eb36d7a0775b"
    );

    let c = unblind_signature(&c_prime, &bm.blinder, &a_pk).unwrap();
    assert_eq!(
        hex::encode(c.to_bytes()),
        "03c9ac52536e99fa21f6a79df975d914cdc4add0339a5d9ab79d7c15c1438b88a1",
        "unblinding diverged"
    );

    assert!(
        verify_signature_with_privkey(secret, &c, &a).unwrap(),
        "C must equal a*Y"
    );
}

/// The DLEQ proof (e, s) generated over (B', C', A) verifies here and in
/// gonuts; any tampered s must fail in both.
#[test]
fn cross_dleq_proof_vector_1() {
    let b_prime = pk("02146df70db068304f8c8416d463991af9fa9a47d84be0e64bbef39636b17619cb");
    let c_prime = pk("0386c681c4515c1f32cb53d4cfc00cf57debe6d62a1cc52a84afe8eb36d7a0775b");
    let a_pk = pk("02989c0b76cb563971fdc9bef31ec06c3560f3249d6ee9e5d83c57625596e05f6f");
    let e = sk_from_hex("b528fc8fe455734e88c6ec5b1c1d3bd7200657925cf9e1d371a1354985e13e12");
    let s = sk_from_hex("2c17665668eaa4ef6d1d82daf181eaef09b9b8b50f3753524bbc93ed230e9d19");

    assert!(
        verify_dleq(&b_prime, &c_prime, &e, &s, &a_pk).unwrap(),
        "cross-vector DLEQ proof must verify"
    );

    let s_tampered = sk(9);
    assert!(
        !verify_dleq(&b_prime, &c_prime, &e, &s_tampered, &a_pk).unwrap(),
        "tampered s must be rejected"
    );
}

/// The secret-convention contract end to end: a hex-looking secret STRING
/// must be blinded and verified as its ASCII bytes across the full DHKE
/// chain, and hex-decoding it first must NOT verify (the 2026-09-04
/// session found the firmware swap path and host-mint-tool doing exactly
/// that — self-consistent against the demo signer, rejected by every
/// string-convention mint and gate).
#[test]
fn cross_secret_convention_hex_looking_string() {
    let secret_str = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef";
    let a = sk(9);

    let bm = blind_message(secret_str.as_bytes(), Some(sk(21))).unwrap();
    let c_prime = sign_message(&a, &bm.blinded);
    let c = unblind_signature(&c_prime, &bm.blinder, &a.public_key()).unwrap();

    assert!(
        verify_signature_with_privkey(secret_str.as_bytes(), &c, &a).unwrap(),
        "string-bytes convention must verify"
    );

    let decoded = hex::decode(secret_str).unwrap();
    assert!(
        !verify_signature_with_privkey(&decoded, &c, &a).unwrap(),
        "hex-decoded convention must NOT verify the same proof"
    );
}
