//! NUT-01: Mint Public Keys
//!
//! Defines the response format for `GET /v1/keys` — the mint's active
//! public keyset(s), mapping denomination amounts to public keys.
//!
//! Reference: https://github.com/cashubtc/nuts/blob/main/01.md

#[cfg(not(feature = "std"))]
use alloc::string::String;
#[cfg(not(feature = "std"))]
use alloc::vec::Vec;

use crate::keypair::PublicKey;
use minicbor::{Decode, Encode};

/// A single denomination-to-public-key mapping within a keyset.
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
// NUT #01: Keys in Keysets are maps of the form `{<amount_1> : <mint_pubkey_1>, <amount_2> : <mint_pubkey_2>, ...}` for each `<amount_i>` of the amounts the mint `Bob` supports and the corresponding public key `<mint_pubkey_1>`, that is `K_i` (see [NUT-00][00]). The mint **MUST** use the [compressed Secp256k1 public key format](https://learnmeabitcoin.com/technical/public-key#public-key-format) to represent its public keys.
pub struct KeyPair {
    /// Power-of-two denomination (e.g. 1, 2, 4, 8, …).
    #[n(0)]
    pub amount: u64,
    /// The mint's public key for this denomination.
    #[n(1)]
    pub pubkey: PublicKey,
}

/// A complete keyset with its ID, unit, and denomination keys (NUT-01).
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
// NUT #01: Keysets are generated by the mint. The mint is free to use any key generation method they like. Each keyset is identified by its keyset `id` which can be computed by anyone from its public keys (see [NUT-02][02]).
pub struct KeySet {
    /// Keyset identifier (derived per NUT-02).
    #[n(0)]
    pub id: String,
    /// Unit of the keyset (e.g. "sat").
    #[n(1)]
    pub unit: String,
    /// The denomination keys in this keyset, sorted by amount ascending.
    #[n(2)]
    pub keys: Vec<KeyPair>,
}

/// Response for `GET /v1/keys` (NUT-01).
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct KeysResponse {
    #[n(0)]
    pub keysets: Vec<KeySet>,
}
