#!/usr/bin/env python3
"""
Boot Splash Asset Generator for Micronuts

Downloads / reads the official Cashu nut logo and produces:
  1. Nearest-neighbor downscaled PNG tile masters at several sizes
  2. RGB565 raw binary files for each tile (for direct framebuffer use)
  3. A single Rust source file (boot_splash_assets.rs) that embeds the
     RGB565 data as const arrays

Source logo:
  - cashubtc/docs.cashu.space  public/homepage/nut-logo.png
  - Vendored copy at firmware/assets/nut-logo-original.png  (707 x 809 RGBA)

All downscaling uses NEAREST-NEIGHBOR to preserve pixel crispness.
The logo has a transparent background; we composite onto black (#000000)
before converting to RGB565.

Usage:
    python3 scripts/generate_assets.py

Output directory: firmware/assets/generated/
"""

import os
import struct
import sys

from PIL import Image

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_IMAGE = os.path.join(REPO_ROOT, "firmware", "assets", "nut-logo-original.png")
OUT_DIR = os.path.join(REPO_ROOT, "firmware", "assets", "generated")
RUST_OUT = os.path.join(REPO_ROOT, "firmware", "src", "boot_splash_assets.rs")

# Tile catalog: name -> target height in pixels.
# Width is computed to preserve aspect ratio.
# These are tuned for an 800x480 display tiled grid.
TILE_CATALOG = {
    "tiny":   24,   # ~28x24 — very dense grid, retro wallpaper feel
    "small":  40,   # ~35x40 — medium-dense, good default
    "medium": 64,   # ~56x64 — balanced size
    "large":  96,   # ~84x96 — big logos, fewer per row
}

# Background color to composite transparent logo onto (black)
BG_COLOR = (0, 0, 0, 255)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    """Convert 8-bit RGB to 16-bit RGB565 (little-endian stored)."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def composite_on_black(img: Image.Image) -> Image.Image:
    """Flatten RGBA image onto a black background, return RGB image."""
    bg = Image.new("RGBA", img.size, BG_COLOR)
    bg.paste(img, (0, 0), img)
    return bg.convert("RGB")


def image_to_rgb565_bytes(img: Image.Image) -> bytes:
    """Convert an RGB PIL Image to RGB565 little-endian bytes."""
    pixels = img.load()
    w, h = img.size
    data = bytearray(w * h * 2)
    idx = 0
    for y in range(h):
        for x in range(w):
            r, g, b = pixels[x, y]
            val = rgb888_to_rgb565(r, g, b)
            struct.pack_into("<H", data, idx, val)
            idx += 2
    return bytes(data)


def generate_tile(src: Image.Image, name: str, target_h: int) -> dict:
    """Resize logo to target height (nearest-neighbor), save PNG + RGB565."""
    orig_w, orig_h = src.size
    scale = target_h / orig_h
    target_w = max(1, round(orig_w * scale))

    # Nearest-neighbor resize
    resized = src.resize((target_w, target_h), Image.NEAREST)

    # Save PNG master
    png_path = os.path.join(OUT_DIR, f"nut-{name}.png")
    resized.save(png_path)

    # Flatten onto black and convert to RGB565
    flat = composite_on_black(resized)
    rgb565_data = image_to_rgb565_bytes(flat)

    bin_path = os.path.join(OUT_DIR, f"nut-{name}.rgb565")
    with open(bin_path, "wb") as f:
        f.write(rgb565_data)

    print(f"  {name:8s}: {target_w}x{target_h}  ({len(rgb565_data)} bytes RGB565)")
    return {
        "name": name,
        "width": target_w,
        "height": target_h,
        "data": rgb565_data,
    }


def write_rust_source(tiles: list):
    """Generate firmware/src/boot_splash_assets.rs with embedded RGB565 data."""
    lines = []
    lines.append("//! Auto-generated boot splash tile assets — DO NOT EDIT BY HAND")
    lines.append("//!")
    lines.append("//! Generated by: scripts/generate_assets.py")
    lines.append("//! Source: firmware/assets/nut-logo-original.png (official Cashu nut logo)")
    lines.append("//!")
    lines.append("//! Each tile is stored as a const &[u16] in native RGB565 format.")
    lines.append("//! Pixel layout: row-major, top-to-bottom, left-to-right.")
    lines.append("")
    lines.append("/// Descriptor for one tile-size variant.")
    lines.append("#[derive(Clone, Copy)]")
    lines.append("pub struct TileAsset {")
    lines.append("    pub width: u16,")
    lines.append("    pub height: u16,")
    lines.append("    pub data: &'static [u16],")
    lines.append("}")
    lines.append("")

    for tile in tiles:
        name_upper = tile["name"].upper()
        w = tile["width"]
        h = tile["height"]
        data = tile["data"]
        pixel_count = w * h

        # Convert bytes to u16 array literal
        u16_values = []
        for i in range(0, len(data), 2):
            val = struct.unpack_from("<H", data, i)[0]
            u16_values.append(f"0x{val:04X}")

        lines.append(f"/// Tile: {tile['name']} — {w}x{h} pixels ({pixel_count} u16 values)")
        lines.append(f"#[allow(clippy::unreadable_literal)]")
        lines.append(f"const TILE_{name_upper}_DATA: [u16; {pixel_count}] = [")

        # Write in rows of 16 for readability
        row_size = 16
        for chunk_start in range(0, len(u16_values), row_size):
            chunk = u16_values[chunk_start:chunk_start + row_size]
            lines.append("    " + ", ".join(chunk) + ",")

        lines.append("];")
        lines.append("")
        lines.append(f"pub const TILE_{name_upper}: TileAsset = TileAsset {{")
        lines.append(f"    width: {w},")
        lines.append(f"    height: {h},")
        lines.append(f"    data: &TILE_{name_upper}_DATA,")
        lines.append(f"}};")
        lines.append("")

    # Catalog array
    lines.append("/// All available tile sizes, ordered smallest to largest.")
    lines.append(f"pub const TILE_CATALOG: [TileAsset; {len(tiles)}] = [")
    for tile in tiles:
        name_upper = tile["name"].upper()
        lines.append(f"    TILE_{name_upper},")
    lines.append("];")
    lines.append("")

    with open(RUST_OUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    total_bytes = sum(len(t["data"]) for t in tiles)
    print(f"\nRust source written to: {RUST_OUT}")
    print(f"Total asset data: {total_bytes} bytes ({total_bytes // 1024} KiB)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    print(f"Loading source image: {SRC_IMAGE}")
    src = Image.open(SRC_IMAGE).convert("RGBA")
    print(f"  Original size: {src.size[0]}x{src.size[1]}")
    print()

    # Generate tiles sorted by size
    sorted_names = sorted(TILE_CATALOG.keys(), key=lambda k: TILE_CATALOG[k])
    tiles = []
    print("Generating tiles:")
    for name in sorted_names:
        target_h = TILE_CATALOG[name]
        tile = generate_tile(src, name, target_h)
        tiles.append(tile)

    print()

    # Write Rust source
    write_rust_source(tiles)

    print("\nDone! Assets ready for firmware build.")
    print("Run `cargo build` in firmware/ to verify.")


if __name__ == "__main__":
    main()
